#!/usr/bin/env bash

# 1. CD into the project folder
cd "$HOME/Documents/yurrr" || exit 1

# 2. Launch nix-shell with Euporie targeting a new session or a specific file
nix-shell <<-EOF
  source .venv/bin/activate
  euporie notebook
EOF
