foreground            #e6e1e9
background            #141318
selection_foreground  #34275e
selection_background  #cdbdff
cursor                #e6e1e9

# Black
color0  #141318
color8  #938f99

# Red
color1  #ffb4ab
color9  #ffb4ab

# Green / Primary
color2  #cdbdff
color10 #cdbdff

# Yellow / Secondary
color3  #cbc3dc
color11 #cbc3dc

# Blue / Tertiary
color4  #eeb8c9
color12 #eeb8c9

# Magenta
color5  #4b3e76
color13 #4b3e76

# Cyan
color6  #494458
color14 #494458

# White
color7  #e6e1e9
color15 #cac4cf
