foreground            #f1dfda
background            #1a110f
selection_foreground  #561f0f
selection_background  #ffb5a0
cursor                #f1dfda

# Black
color0  #1a110f
color8  #a08c87

# Red
color1  #ffb4ab
color9  #ffb4ab

# Green / Primary
color2  #ffb5a0
color10 #ffb5a0

# Yellow / Secondary
color3  #e7bdb2
color11 #e7bdb2

# Blue / Tertiary
color4  #d9c58d
color12 #d9c58d

# Magenta
color5  #723523
color13 #723523

# Cyan
color6  #5d4037
color14 #5d4037

# White
color7  #f1dfda
color15 #d8c2bc
