foreground            #ffffff
background            #151313
selection_foreground  #2f2228
selection_background  #eed6df
cursor                #ffffff

# Black
color0  #151313
color8  #bbafb3

# Red
color1  #ffd2cc
color9  #ffd2cc

# Green / Primary
color2  #eed6df
color10 #eed6df

# Yellow / Secondary
color3  #e6d9dd
color11 #e6d9dd

# Blue / Tertiary
color4  #dddbe9
color12 #dddbe9

# Magenta
color5  #9f8b94
color13 #9f8b94

# Cyan
color6  #998e91
color14 #998e91

# White
color7  #ffffff
color15 #e6d9dd
