
# 1. Add inner padding so the text doesn't hit the edges
window_padding_width 23

# 2. Hide titlebar and window decorations
hide_window_decorations yes

# 3. Enable transparency (Hyprglass will apply blur to this layer)
background_opacity 
 
# 4. Default shell
shell fish

# 5. Font size
font_size 9.3

# 6. Live config reload (Kitty reloads automatically on save)
# Auto-reload is enabled by default in Kitty.

# 7. Import color scheme
include colors.conf

confirm_os_window_close 0

cursor_trail 3
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

cursor_shape beam
cursor_blink_interval 0.5
cursor_stop_blinking_after 15.0
