
window_padding_width 20

hide_window_decorations yes

background_opacity 0.8
shell fish

font_size 9


# colors
include colors.conf

confirm_os_window_close 0

cursor_trail 3
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

cursor_shape beam
cursor_blink_interval 0.5
cursor_stop_blinking_after 15.0
include ~/.cache/colors-kitty.conf
allow_remote_control yes
listen_on unix:/tmp/kitty
include colors-matugen.conf
