[config]
reload_apps = true
mode = "dark"

[templates.rofi_launcher]
input_path = '~/.config/matugen/templates/colors-rofi.rasi'
output_path = '~/.cache/colors-rofi.rasi'

[templates.rofi_wallpaper]
input_path = '~/.config/matugen/templates/wallpaper-rofi.rasi'
output_path = '~/.cache/wallpaper-rofi.rasi'
