-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "retrosmart-xcursor-black-shadow")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
    animations = {
        enabled = true,
    },
    decoration = {
        dim_inactive = true,
        dim_strength = 0.15,
        rounding = 3,
    },
    general = {
        allow_tearing = true,
        border_size = 2,
        col = {
            active_border = "0xffffffff",
            inactive_border = "0xff77767b",
        },
        extend_border_grab_area = 16,
        gaps_in = 6,
        gaps_out = 13,
        layout = "scrolling",
        resize_on_border = false,
    },
    gestures = {
        workspace_swipe_forever = true,
    },
    input = {
        accel_profile = "adaptive",
        numlock_by_default = true,
    },
    master = {
        allow_small_split = false,
        mfact = 0.5,
        smart_resizing = false,
    },
    misc = {
        vrr = 1,
    },
})

-- Monitors
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "1920x1080@240.00Hz",
    position = "280x1440",
    scale = 1,
    cm = "srgb",
    sdrbrightness = 1,
    sdr_min_luminance = 0.46,
    sdr_max_luminance = 959,
    min_luminance = 0.45,
    max_luminance = 948,
    max_avg_luminance = 928,
})

-- Keybinds
hl.unbind("SUPER + X")
hl.bind("SUPER + X", hl.dsp.exec_cmd("hyprset"))

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("kitty")
end)
