autogenerated = false

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

hl.config({ autogenerated = false })

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")

hl.plugin.load("/run/current-system/sw/lib/hyprglass.so")

hl.env("GTK_THEME", "Adwaita:dark")
hl.env("QT_STYLE_OVERRIDE", "adwaita-dark")



------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
    output   = "eDP-1",
    mode     = "preferred",
    position = "auto",
    scale    = 1.0,
})


---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal    = "kitty"
local fileManager = "dolphin"
local menu        = "hyprlauncher"


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--


-- =========================================================================
-- 1. HYPRGLASS PLUGIN SETUP (Top-level scope: re-evaluates on hyprctl reload)
-- =========================================================================
if hl and hl.plugin and hl.plugin.hyprglass then
  local hg = hl.plugin.hyprglass

  -- 1. Define Presets
  hg.preset("hard_blur", {
    glass_opacity = 0.9,
    blur_strength = 0.7,
    blur_iterations = 7,
    refraction_strength = 0.3,
    chromatic_aberration = 0.3,
    fresnel_strength = 4.0,
    specular_strength = 0.3,
    lens_distortion = 0.1,
    dark = { brightness = 1.1, contrast = 1.3, saturation = 1.2 },
  })

  hg.preset("frosted_glass", {
    glass_opacity = 1.2,

    -- Smooth, high-pass blur
    blur_strength = 0.8,
    blur_iterations = 5,           -- Extra passes for ultra-smooth blur

    -- Subtle Tint (RGBA Hex: #111625 at ~12% opacity)
    --tint_color = 0x1116251F,       -- Soft dark-slate tint

    -- Optics & Material Highlights
    refraction_strength = 0.04,
    chromatic_aberration = 0.02,
    fresnel_strength = 0.20,
    specular_strength = 0.10,
    lens_distortion = 0.0,

    -- Background Post-Processing
    dark = {
      brightness = 1.2,
      contrast = 1.08,
      saturation = 1.15,
    },
  })


  -- 2. Apply Global Plugin Config
  hg.config({
    default_theme = "dark",
    default_preset = "frosted_glass",
    layers = { enabled = 1 },
    dark = { brightness = 0.85, contrast = 1.1 },
  })

  -- 4. Success Notification
  if hl.notification then
    hl.notification.create({
      text = "hyprglass configured: frosted_glass",
      timeout = 3000,
      icon = "ok",
    })
  end

else
  if hl and hl.notification then
    hl.notification.create({
      text = "hyprglass plugin not loaded",
      timeout = 5000,
      icon = "warning",
    })
  end
end
-- =========================================================================
-- 2. HYPRLAND COMPOSITOR CONFIG & RULES
-- =========================================================================
hl.config({
  decoration = {
    blur = {
      new_optimizations = false, -- Required for proper glass/shader rendering
    },
  },
})

hl.window_rule({
  match = { class = "^(kitty)$" },
  opacity = "0.5 0.5"
})

-- =========================================================================
-- 3. AUTOSTART COMMANDS (Only fires once on compositor start)
-- =========================================================================
hl.on("hyprland.start", function ()
  hl.exec_cmd("waybar")
  hl.exec_cmd("waypaper --restore")
end)


------------------------------
--------- HYPRLOCK------------
------------------------------
local hyprlock_config = [[
# Background - Pure Black
background {
    monitor =
    color = rgb(0, 0, 0)
}

# TUI Window Container Box
shape {
    monitor =
    size = 460, 220
    color = rgb(15, 15, 15)
    border_size = 2
    border_color = rgb(255, 255, 255) # Sharp white border
    rounding = 0
    position = 0, 0
    halign = center
    valign = center
}

# TUI Header: Hostname & Title
label {
    monitor =
    text = nixos login:
    color = rgb(255, 255, 255)
    font_size = 13
    font_family = JetBrains Mono
    position = -160, 75
    halign = center
    valign = center
}

# Live TUI Clock
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%Y-%m-%d %H:%M:%S')"
    color = rgb(160, 160, 160)
    font_size = 12
    font_family = JetBrains Mono
    position = 110, 75
    halign = center
    valign = center
}

# User Name Line
label {
    monitor =
    text = user: suupatruupa
    color = rgb(240, 240, 240)
    font_size = 13
    font_family = JetBrains Mono
    position = -130, 20
    halign = center
    valign = center
}

# Password Line Label
label {
    monitor =
    text = password:
    color = rgb(240, 240, 240)
    font_size = 13
    font_family = JetBrains Mono
    position = -146, -30
    halign = center
    valign = center
}

# Terminal Password Input Box
input-field {
    monitor =
    size = 220, 32
    outline_thickness = 1
    dots_size = 0.28
    dots_spacing = 0.3
    dots_center = false
    outer_color = rgb(255, 255, 255)
    inner_color = rgb(0, 0, 0)
    font_color = rgb(255, 255, 255)
    fade_on_empty = false
    placeholder_text = <span foreground="##888888">...</span>
    hide_input = false
    rounding = 0
    
    position = 55, -30
    halign = center
    valign = center
}
]]

-- Write hyprlock.conf on Hyprland startup
local file = io.open(os.getenv("HOME") .. "/.config/hypr/hyprlock.conf", "w")
if file then
    file:write(hyprlock_config)
    file:close()
end





-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")


-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")



-- =========================================================================
-- Hyprglass Plugin Configuration & Window Rules
-- =========================================================================

-- Window opacity rules
-- Catch-all first (lowest priority — gets overridden by more specific matches below)
hl.window_rule({
  match = { class = ".*" },
  opacity = "0.85 0.85"
})

hl.window_rule({
  match = { class = "^(kitty)$" },
  opacity = "0.85 0.85"
})

-- Full opacity exceptions — must come last so they win over the catch-all
hl.window_rule({
  match = {
    class = "^(steam_app_.*|wine|.*zenless_zone_zero.*|gamescope|org.prismlauncher.PrismLauncher|Spotify)$"
  },
  opacity = "1.0 1.0"
})


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 10,
        gaps_out = 20,

        -- 1. Set border to 0 for the completely borderless look in image_f663df.png
        border_size = 0,

        col = {
            active_border   = "rgba(595959aa)",
            inactive_border = "rgba(595959aa)",
        },

        resize_on_border = false,
        allow_tearing = false,
        layout = "dwindle",
    },

    decoration = {
        -- 2. Bump up rounding for those smooth, bubbly card corners
        rounding       = 16,
        rounding_power = 2,

        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        -- 3. Enhance the shadow parameters to make the floating window pop
        shadow = {
            enabled      = true,
            range        = 25,
            render_power = 3,
            color        = "rgba(00000055)",
        },

        blur = {
            enabled   = true,
            size      = 3,
            passes    = 1,
            vibrancy  = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },
})
-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

-- Default springs
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 71.2633, dampening = 15.8273644 })

hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 4.1,  spring = "easy",         style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 7,    bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = -1,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = false, -- If true disables the random hyprland logo / anime girl background. :(
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = true ,
            tap_to_click = true ,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------
-- Force calendar and system language to English
-- Execute background environment locale setups natively on boot
hl.dsp.exec_cmd("hyprctl setenv LANG en_US.UTF-8")
hl.dsp.exec_cmd("hyprctl setenv LC_TIME en_US.UTF-8")
hl.dsp.exec_cmd("hyprctl setenv LC_ALL en_US.UTF-8")

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
local closeWindowBind = hl.bind(mainMod .. " + C", hl.dsp.window.close())
-- closeWindowBind:set_enabled(false)
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V", hl.dsp.window.fullscreen({ mode = 1, action = "toggle" }))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))    -- dwindle only
hl.bind(mainMod .. " + space", hl.dsp.exec_cmd("wofi --show drun"))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("flatpak run app.zen_browser.zen"))
hl.bind("SUPER + SUPER_L", hl.dsp.global("caelestia:launcher"), { ignore_mods = true })
hl.bind("Print", hl.dsp.exec_cmd('grim -g "$(slurp)" - | swappy -f -'))
hl.bind("XF86SelectiveScreenshot", hl.dsp.exec_cmd('grim -g "$(slurp)" - | swappy -f -'))
hl.bind("SHIFT + Print", hl.dsp.exec_cmd('grim - | swappy -f -'))

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- Alt+Tab: cycle windows, bring active to top (works for floating too)
hl.bind("ALT + Tab", function()
  hl.dispatch(hl.dsp.window.cycle_next())
  hl.dispatch(hl.dsp.window.bring_to_top())
end)
-- Move active window with mainMod + SHIFT + arrow keys
hl.bind(mainMod .. " + SHIFT + left",  hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({ direction = "right" }))
hl.bind(mainMod .. " + SHIFT + up",    hl.dsp.window.move({ direction = "up" }))
hl.bind(mainMod .. " + SHIFT + down",  hl.dsp.window.move({ direction = "down" }))

-- spotify
hl.bind(mainMod .. " + O", function()
  hl.exec_cmd("spotify")
end)

-- vs code
hl.bind(mainMod .. " + N", function()
  hl.exec_cmd(".local/bin/yurrr")
end)

-- euporie
--hl.bind(mainMod .." + T", function()
-- hl.exec_cmd("~/.local/bin/yeup")
--end)

-- rofi app launcher
hl.bind(mainMod .. " + K", function()
  hl.exec_cmd("rofi -show drun -theme ~/.config/rofi/config.rasi")
end)



-- obsidian
hl.bind(mainMod .. " + I", function()
 hl.exec_cmd("obsidian &")
end)

-- lock
hl.bind(mainMod .. " + L", function()
  hl.exec_cmd("hyprlock")
end)


-- waypaper
hl.bind("SUPER + SHIFT + W", hl.dsp.exec_cmd("waypaper"))

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,             hl.dsp.focus({ workspace = i}))
    hl.bind(mainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i }))
end
-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),                  { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),                  { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)


-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

--waypaper
hl.window_rule({
    name = "waypaper-float",
    match = { class = "waypaper" },
    float = true,
    size = "700 850",
    move = "onscreen center",
})

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})
